config/routes.rb
Rails.application.routes.draw do
  get 'home/new'
  get 'users/show'
  get 'books/show'
  get 'books/index' => 'books#index'
  get 'books/new'
  get 'books/edit'
  get 'home/index'
  devise_for :users
  #ホーム画面に向かう
  root :to => 'homes#index'
  resources :books, only: [:show, :edit, :update, :index, :destroy, :create]
  resources :users, only: [:show, :edit, :update, :index]
  get 'home/about' => 'homes#about'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  #postsがuserに対して1:N
  has_many :books, dependent: :destroy
  attachment :profile_image

  validates :name, presence: true
  validates :name,  length: { maximum: 20 }
  validates :name,  length: { minimum: 2 }
  validates :introduction,  length: { maximum: 50 }
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end

end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_user!
	def show
		@user = User.find(params[:id])
        @books = @user.books
	  	@book = Book.new
  	end
	def edit
		@user = User.find(params[:id])
		if current_user.id != @user.id
			redirect_to user_path(current_user.id)
		end
	end
	def update
		@user = User.find(params[:id])
    	if @user.update(user_params)
    		redirect_to user_path(@user.id)
    		flash[:notice] = "You have updated user successfully."
    	else
    		render 'users/edit'
    	end
	end
	def index
		@users = User.all
		@user = User.find_by(id: current_user.id)
		@book = Book.new
	end
	private
	def user_params
	    params.require(:user).permit(:name, :profile_image, :introduction)
	end
	def update_resource(resource, params)
	    resource.update_without_password(params)
	end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<h2>User info</h2>
<%=  flash[:notice]  %>
<%= form_for(@user) do |f| %>
<% if @user.errors.any? %>
  <div id="error_explanation" class="alert alert-danger">
  	<p>error prohibited this obj from being saved</p>
    <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>
	  <label>name</label>
	  <%= f.text_field :name %>
	  <label>Image</label>
	  <%= f.attachment_field :profile_image %>
	  <label>Introduction</label>
	  <%= f.text_area :introduction %><br>
	  <%= f.submit "Update User" %>
<% end %>

app/views/users/index.html.erb
<div class="container">
<div class="row">
<div class="col-xs-3">
<h2>User info</h2>
<div class="profile-container">
    <%= attachment_image_tag @user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %>
    <h3 class="profile-name">name     <%= @user.name %></h3>
    <p>introduction     <%= @user.introduction %></p>
	<% if @user.id == current_user.id %>
		<%= link_to edit_user_path(@user), method: :get do %>
        <button class="btn btn-default" aria-label="Left Align" type="button"><span class="glyphicon glyphicon glyphicon-wrench" aria-hidden="true"></span></button><% end %>
    <% else %>
    	<%= link_to user_path(current_user.id), method: :get do %>
    	<button class="btn btn-default" aria-label="Left Align" type="button"><span class="glyphicon glyphicon glyphicon-wrench" aria-hidden="true"></span></button><% end %>
    <% end %>
</div>
<div class="newbook">
	<h1 class="newbook-headline">New book</h1>
	<%=  form_for(@book) do |f|  %>
	    <h4>Title</h4>
	    <%= f.text_field :title %>
	    <h4 class="newbook-body">Opinion</h4>
	    <%= f.text_area :body %><br>
	    <%= f.submit 'Create book' %>
	<% end %>
</div>
</div>
<div class="col-xs-9">
<h2>Users</h2>
<table class="table table-striped">
	<thead>
    	<tr>
			<th>image</th>
			<th>name</th>
			<th></th>
		</tr>
	</thead>
	<tbody>
		<%  @users.each do |user|  %>
			<tr>
				<td><%= attachment_image_tag user, :profile_image, :fill, 85, 85, format: 'jpeg', fallback: "no_image.jpg" %></td>
				<td><%=  user.name  %></td>
				<td><%= link_to "Show", user_path(user.id) %></td>
			</tr>
		<%  end  %>
	</tbody>
</table>
</div>
</div>
</div>

app/views/users/show.html.erb
<p class="notice"><%= notice %></p>
<div class="container">
<div class="row">
<div class="col-xs-3">
<h2>User info</h2>
<div class="profile-container">
    <%= attachment_image_tag @user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %>
    <h3 class="profile-name">name     <%= @user.name %></h3>
    <p>introduction     <%= @user.introduction %></p>
	<% if @user.id == current_user.id %>
		<%= link_to edit_user_path(@user), method: :get do %>
        <button class="btn btn-default" aria-label="Left Align" type="button"><span class="glyphicon glyphicon glyphicon-wrench" aria-hidden="true"></span></button><% end %>
    <% else %>
    	<%= link_to user_path(current_user.id), method: :get do %>
    	<button class="btn btn-default" aria-label="Left Align" type="button"><span class="glyphicon glyphicon glyphicon-wrench" aria-hidden="true"></span></button><% end %>
    <% end %>
</div>
<div class="newbook">
	<h1 class="newbook-headline">New book</h1>
	<%=  form_for(@book) do |f|  %>
	    <h4>Title</h4>
	    <%= f.text_field :title %>
	    <h4 class="newbook-body">Opinion</h4>
	    <%= f.text_area :body %><br>
	    <%= f.submit 'Create Book' %>
	<% end %>
</div>
</div>
<div class="col-xs-9">
<h2>Books</h2>
<table class="table table-striped">
	<thead>
    	<tr>
    		<th></th>
			<th>title</th>
			<th>body</th>
		</tr>
	</thead>
	<tbody>
		<%  @books.each do |book|  %>
			<tr>
				<td><%= attachment_image_tag @user, :profile_image, :fill, 85, 85, format: 'jpeg', fallback: "no_image.jpg" %></td>
				<td><%=  link_to "#{book.title}", book_path(book.id)  %></td>
				<td><%=  book.body  %></td>
			</tr>
		<%  end  %>
	</tbody>
</table>
</div>
</div>
</div>