config/routes.rb
Rails.application.routes.draw do
  get 'home/new'
  get 'users/show'
  get 'books/show'
  get 'books/index' => 'books#index'
  get 'books/new'
  get 'books/edit'
  get 'home/index'
  devise_for :users
  #ホーム画面に向かう
  root :to => 'homes#index'
  resources :books, only: [:show, :edit, :update, :index, :destroy, :create]
  resources :users, only: [:show, :edit, :update, :index]
  get 'home/about' => 'homes#about'
end

app/models/book.rb
class Book < ApplicationRecord
	#userに対してN:1
	belongs_to :user
	validates :title, presence: true, length: { maximum: 50 }
	validates :body, presence: true, length: { maximum: 200 }
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!
  def index
    @books = Book.all
    @book = Book.new
    @user = User.find_by(id: current_user.id)
  end

  def show
  	@book = Book.find(params[:id])
    @user = @book.user
    @books = Book.new
  end


  def create
  	@book = Book.new(book_params)
  	@book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book)
      flash[:notice] = "You have created book successfully."
    else
      @user = User.find_by(id: current_user.id)
      @books = Book.all
      render 'books/index'
    end
  end
  def edit
    @book = Book.find(params[:id])
    if current_user.id != @book.user_id
      redirect_to books_path
    end
  end
  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book)
      flash[:notice] = "You have updated book successfully."
    else
      render 'books/edit'
    end
  end
  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to user_path(current_user.id)
  end
  private
    def book_params
      params.require(:book).permit(:title, :body)
    end
end

app/views/books/edit.html.erb
<h2>Editing Book</h2>

<%= form_for(@book) do |f| %>
<% if @book.errors.any? %>
  <div id="error_explanation" class="alert alert-danger">
  	<p>error prohibited this obj from being saved</p>
    <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>
    <h4>Title</h4>
    <%= f.text_field :title %>
    <h4>Opinion</h4>
    <%= f.text_area :body %>
    <%= f.submit 'Update Book' %>
<% end %>
<%=  link_to "Show", book_path(@book.id)  %>|
<%=  link_to "Back", books_path %>

app/views/books/index.html.erb
<% if @book.errors.any? %>
  <div id="error_explanation" class="alert alert-danger">
    <ul>
      <% @book.errors.full_messages.each do |message| %>
      	<P>error</P>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>
<div class="container">
<div class="row">
<div class="col-xs-3">

<h2>User info</h2>
<div class="profile-container">
    <%= attachment_image_tag @user, :profile_image, :fill, 100, 100, format: 'jpeg',  fallback: "no_image.jpg" %>
    <h3 class="profile-name">name     <%= @user.name %></h3>
    <p>introduction     <%= @user.introduction %></p>
	<% if @user.id == current_user.id %>
		<%= link_to edit_user_path(@user), method: :get do %>
        <button class="btn btn-default" aria-label="Left Align" type="button"><span class="glyphicon glyphicon glyphicon-wrench" aria-hidden="true"></span></button><% end %>
    <% else %>
    	<%= link_to user_path(current_user.id), method: :get do %>
    	<button class="btn btn-default" aria-label="Left Align" type="button"><span class="glyphicon glyphicon glyphicon-wrench" aria-hidden="true"></span></button><% end %>
    <% end %>
</div>
<div class="newbook">
	<h1 class="newbook-headline">New book</h1>
	<%=  form_for(@book) do |f|  %>
	    <h4>Title</h4>
	    <%= f.text_field :title %>
	    <h4 class="newbook-body">Opinion</h4>
	    <%= f.text_area :body %><br>
	    <%= f.submit 'Create Book' %>
	<% end %>
</div>
</div>
<div class="col-xs-9">
<h3>Books</h3>
<table class="table table-striped">
	<thead>
    	<tr>
    		<th></th>
			<th>Title</th>
			<th>Opinion</th>
		</tr>
	</thead>
	<tbody>
		<%  @books.each do |book|  %>
			<tr>
				<td><%= link_to user_path(book.user), method: :get do %><%= attachment_image_tag book.user, :profile_image, :fill, 85, 85, format: 'jpeg', fallback: "no_image.jpg" %><% end %></td>
				<td><%=  link_to "#{book.title}", book_path(book.id)  %></td>
				<td><%=  book.body  %></td>
			</tr>
		<%  end  %>
	</tbody>
</table>
</div>
</div>
</div>

app/views/books/show.html.erb
<%=  flash[:notice]  %>
<div class="container">
<div class="row">
<div class="col-xs-3">
<h2>User info</h2>
<div class="profile-container">
    <%= attachment_image_tag @user, :profile_image, :fill, 100, 100, format: 'jpeg',  fallback: "no_image.jpg" %>
    <h3 class="profile-name">name     <%= @user.name %></h3>
    <p>introduction     <%= @user.introduction %></p>
	<% if @user.id == current_user.id %>
		<%= link_to edit_user_path(@user), method: :get do %>
        <button class="btn btn-default" aria-label="Left Align" type="button"><span class="glyphicon glyphicon glyphicon-wrench" aria-hidden="true"></span></button><% end %>
    <% else %>
    	<%= link_to user_path(current_user.id), method: :get do %>
    	<button class="btn btn-default" aria-label="Left Align" type="button"><span class="glyphicon glyphicon glyphicon-wrench" aria-hidden="true"></span></button><% end %>
    <% end %>
</div>
<div class="newbook">
	<h1 class="newbook-headline">New Book</h1>
	<%=  form_for(@books) do |f|  %>
	    <h4>Title</h4>
	    <%= f.text_field :title %>
	    <h4 class="newbook-body">Opinion</h4>
	    <%= f.text_area :body %><br>
	    <%= f.submit 'Create book' %>
	<% end %>
</div>
</div>
<div class="col-xs-9">
<h2>Book detail</h2>
<table class="table table-striped">
	<thead>
    	<tr>
    		<th></th>
			<th></th>
			<th></th>
		</tr>
	</thead>
	<tbody>
			<tr>
				<td><%= attachment_image_tag @user, :profile_image, :fill, 85, 85, format: 'jpeg', fallback: "no_image.jpg" %></td>
				<td><%=  @book.title  %></td>
				<td><%=  @book.body  %></td>
				<% if @book.user_id == current_user.id %>
        			<td><%= link_to 'Edit', edit_book_path(@book) %></td>
        			<td><%= link_to 'Destroy', @book, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        		<% end %>
			</tr>
	</tbody>
</table>
<p><%= link_to @user.name, user_path(@user.id) %></p>
</div>
</div>
</div>