config/routes.rb
Rails.application.routes.draw do
  get 'home/new'
  get 'users/show'
  get 'books/show'
  get 'books/index' => 'books#index'
  get 'books/new'
  get 'books/edit'
  get 'home/index'
  devise_for :users
  #ホーム画面に向かう
  root :to => 'homes#index'
  resources :books, only: [:show, :edit, :update, :index, :destroy, :create]
  resources :users, only: [:show, :edit, :update, :index]
  get 'home/about' => 'homes#about'
end

app/views/layouts/_error_books.html.erb
<% if model.errors.any? %>
  <div class="alert alert-warning">
    <ul>
      <% model.errors.full_books.each do |book| %>
        <li><%= book %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <header>
    <nav id="header" class="navbar navbar-default">
      <div class="navbar-header">
        <h2 class="header" >Bookers</h2>
      </div>
      <div class="collapse navbar-collapse" id="navbarEexample">
        <ul class="nav navbar-nav navbar-right"  >
          <% if user_signed_in? %>
            <li class="home-button">
              <span class="glyphicon glyphicon glyphicon-home" aria-hidden="true"><%= link_to 'Home', user_path(current_user.id) %></span>
            </li>
            <li class="home-button">
              <span class="glyphicon glyphicon glyphicon-user" aria-hidden="true"><%= link_to 'Users', users_path %></span>
            </li>
            <li class="home-button">
              <span class="glyphicon glyphicon glyphicon-book" aria-hidden="true"><%= link_to 'Books', books_path %></span>
            </li>
            <li class="home-button">
              <span class="glyphicon glyphicon glyphicon-log-out" aria-hidden="true"><%= link_to "logout", destroy_user_session_path, method: :delete %></span>
            </li>
          <% else %>
            <li class="home-button">
              <span class="glyphicon glyphicon glyphicon-home" aria-hidden="true"><%= link_to 'Home', root_path %></span>
            </li>
            <li class="home-button">
              <span class="glyphicon glyphicon-link" aria-hidden="true"><%= link_to 'About', home_about_path %></span>
            </li>
            <li class="home-button">
              <span class="glyphicon glyphicon-edit" aria-hidden="true"><%= link_to "Sign up", new_user_registration_path %></span>
            </li>
            <li class="home-button">
              <span class="glyphicon glyphicon-log-in" aria-hidden="true"><%= link_to "login", new_user_session_path %></span>
            </li>
          <% end %>
        </ul>
    </nav>
    <%= yield %>
  </header>
</html>